# Site settings
title: Krystyna Banaszewska
description: 'Business Card Page'
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/Kris.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Krystyna Banaszewska'
  email: krysia@banaszewski.pl
  mastodon: tzuehlke@mstdn.social
#  facebook_username: joshgerdes
  github_username:  krissb99
  linkedin_username:  krystyna-banaszewska

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
